[server]
headless = true
port = 8501

[client]
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#FF5F00"
backgroundColor = "#F8F9FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A2C42"
font = "sans serif"

[browser]
gatherUsageStats = false
